name = OS2Forms EGBolig
description = EGBolig form
machine_name = egbolig
version = 1.0-beta1
downloadable = egbolig 7.x-1.0-beta1
author = Bellcom
author_url = http://www.bellcom.com
;screenshots[] = os2forms.png
;logo = os2froms_icon.png

dependencies[i18n] = i18n 7.x-1.13
dependencies[variable] = variable 7.x-2.5
dependencies[entity] = entity 7.x-1.6
dependencies[ctools] = ctools 7.x-1.9
dependencies[pathauto] = pathauto 7.x-1.3
dependencies[l10n_update] = l10n_update 7.x-2.0
dependencies[token] =  token 7.x-1.6
dependencies[services] = services 7.x-3.12
dependencies[webform_service] = webform_service 7.x-3.x-dev
dependencies[services_basic_auth] = services_basic_auth 7.x-1.3
dependencies[webform] = webform 7.x-4.13
dependencies[uuid] = uuid 7.x-1.0-beta1
dependencies[features] = features 7.x-1.0
dependencies[node_export] = node_export 7.x-3.0
dependencies[webform_submission_uuid] = webform_submission_uuid 7.x-1.x-dev
dependencies[libraries] = libraries 7.x-2.2
dependencies[drupal_nemid_login] = drupal_nemid_login
dependencies[securepages] = securepages 7.x-1.0-beta2
dependencies[webform_ssl] = webform_ssl 7.x-1.0-beta1
dependencies[webform_encrypt] = webform_encrypt 7.x-1.1
dependencies[encrypt] = encrypt 7.x-2.1

downloadables[egbolig 7.x-1.0-beta1] = https://github.com/OS2Forms/OS2forms-1.0/blob/master/egbolig.zip?raw=true
downloadables[i18n 7.x-1.13] = http://ftp.drupal.org/files/projects/i18n-7.x-1.13.tar.gz
downloadables[variable 7.x-2.5] = http://ftp.drupal.org/files/projects/variable-7.x-2.5.tar.gz
downloadables[entity 7.x-1.6] = http://ftp.drupal.org/files/projects/entity-7.x-1.6.tar.gz
downloadables[l10n_update 7.x-2.0] = http://ftp.drupal.org/files/projects/l10n_update-7.x-2.0.tar.gz
downloadables[ctools 7.x-1.9] = http://ftp.drupal.org/files/projects/ctools-7.x-1.9.tar.gz
downloadables[token 7.x-1.6] = http://ftp.drupal.org/files/projects/token-7.x-1.6.tar.gz
downloadables[services 7.x-3.12] = http://ftp.drupal.org/files/projects/services-7.x-3.12.tar.gz
downloadables[pathauto 7.x-1.3] = http://ftp.drupal.org/files/projects/pathauto-7.x-1.3.tar.gz
downloadables[webform_service 7.x-3.x-dev] = http://ftp.drupal.org/files/projects/webform_service-7.x-3.x-dev.tar.gz
downloadables[services_basic_auth 7.x-1.3] = http://ftp.drupal.org/files/projects/services_basic_auth-7.x-1.3.tar.gz
downloadables[webform 7.x-4.13] = http://ftp.drupal.org/files/projects/webform-7.x-4.13.tar.gz
downloadables[wfm 7.x-1.x-dev] = http://ftp.drupal.org/files/projects/wfm-7.x-1.x-dev.tar.gz
downloadables[webform_validation 7.x-1.10] = http://ftp.drupal.org/files/projects/webform_validation-7.x-1.10.tar.gz
downloadables[features 7.x-1.0] = http://ftp.drupal.org/files/projects/features-7.x-1.0.tar.gz
downloadables[node_export 7.x-3.0] = http://ftp.drupal.org/files/projects/node_export-7.x-3.0.tar.gz
downloadables[uuid 7.x-1.0-beta1] = http://ftp.drupal.org/files/projects/uuid-7.x-1.0-beta1.tar.gz
downloadables[webform_submission_uuid 7.x-1.x-dev] = http://ftp.drupal.org/files/projects/webform_submission_uuid-7.x-1.x-dev.tar.gz
downloadables[libraries 7.x-2.2] = http://ftp.drupal.org/files/projects/libraries-7.x-2.2.tar.gz
downloadables[drupal_nemid_login] = https://github.com/bellcom/drupal_nemid_login/archive/master.zip?raw=true
downloadables[securepages 7.x-1.0-beta2] = https://ftp.drupal.org/files/projects/securepages-7.x-1.0-beta2.zip
downloadables[webform_ssl 7.x-1.0-beta1] = https://ftp.drupal.org/files/projects/webform_ssl-7.x-1.0-beta1.zip
downloadables[webform_encrypt 7.x-1.1] = https://ftp.drupal.org/files/projects/webform_encrypt-7.x-1.1.zip
downloadables[encrypt 7.x-2.1] = http://ftp.drupal.org/files/projects/encrypt-7.x-2.1.tar.gz
